language: dart
dart:
# Install the latest stable release
- stable
# Install the latest dev release
- dev

dart_task:
- dartfmt: true
- dartanalyzer: --fatal-warnings --fatal-lints lib test
- test: --platform vm

branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
