name: built_json_schema
version: 0.0.1
description: Generate built_value models from json schema
author: Dinesh Ahuja <dev@kabiir.me>
homepage: https://www.github.com/devkabiir/built_json_schema
documentation: # default documentation

dependencies:

dev_dependencies:
  test: ^1.0.0
  pre_commit:
    git: https://github.com/devkabiir/pre_commit/
  built_json_schema_generator:
    git: https://github.com/devkabiir/built_json_schema_generator/
  built_value: ^6.0.0
  build_runner: ^1.0.0
  built_value_generator: ^6.0.0

dependency_overrides:
  built_json_schema_generator:
    path: ../built_json_schema_generator

environment:
  sdk: '>=2.0.0 <3.0.0'
